# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Robot Casserole
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Robot Casserole Team 1736
  A community-based FIRST Robotics team serving the Peoria, IL area
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robotcasserole.org" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Robot Casserole
address_line: Caterpillar PPK Warehouse | 8201 N University St | Peoria, IL
#telephone_number: 1.800.245.356
#fax_number: 1.800.245.357
company_email: frc1736@gmail.com
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3020.853327101029!2d-89.62611158459273!3d40.78723857932384!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x880a5b57095e5fcf%3A0xb9bf7b877517d54b!2s8201%20N%20University%20St%2C%20Peoria%2C%20IL%2061615!5e0!3m2!1sen!2sus!4v1584910538516!5m2!1sen!2sus

# Social Link
facebook_link: http://www.facebook.com
twitter_link: http://www.twitter.com
linkedin_link: http://www.linkedin.com
googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
