###################################################################################
## Welcome to robotcasserole.org, a Jekyll-built static website!
##
## This config file is meant for settings that affect the whole site, values
##  which are expected to set up once and rarely edit after that. 
##  Frequently-updated configuration is found in the `_data` folder.
##
## Because of this, this file is *NOT* reloaded automatically when you use
##  'bundle exec jekyll serve'. If you change this file, please restart the 
##  server process.
###################################################################################

###################################################################################
## Overall Site Configuration
###################################################################################

title: Robot Casserole
email: frc1736@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Robot Casserole Team 1736
  A community-based FIRST Robotics team serving the Peoria, IL area
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robotcasserole.org" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Robot Casserole
address_line_1: Caterpillar PPK Warehouse 
address_line_2: 8201 N University St
address_line_3: Peoria, IL 61615
company_email: frc1736@gmail.com
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d193402.42306640002!2d-89.69480599871426!3d40.763941270753485!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x880a5b57095e5fcf%3A0xb9bf7b877517d54b!2s8201%20N%20University%20St%2C%20Peoria%2C%20IL%2061615!5e0!3m2!1sen!2sus!4v1585321377537!5m2!1sen!2sus

# Social Links
facebook_link: https://www.facebook.com/FRC1736/
twitter_link: https://twitter.com/frc1736
youtube_link: https://www.youtube.com/channel/UCkyFQe46R61o5StqkTYDwdg
instagram_link: https://www.instagram.com/frc1736/
github_link: https://github.com/robotcasserole1736
tba_link: https://www.thebluealliance.com/team/1736

###################################################################################
## Page Image/Video Banner Configurations 
###################################################################################
banner_height: 525px

###################################################################################
## Custom Content Collections 
###################################################################################
collections:

  # Tells the website generator that our history page should be assembled from
  #  all the different individual history year .md files.
  history:


###################################################################################
## Jekyll build configuration 
###################################################################################
markdown: kramdown
plugins:
  - jekyll-feed
